# -*- coding: utf-8 -*-
"""Another copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0bZ8KP9KWC5fcIW-_iwu0hXqRki2Cvo
"""

1+1

a= 10;

b=40

type(b)

type(y)

y=9.7

print("hello SRMCEM")

q=89

t=90

print(q+t)

r=8.9

type(r)

s="abc"

type(s)

s[0]

s[1]

s[2]

s[-1]

s[-2]

s[-3]

s[::-1]

s[0:1:4]

s=True

s=False

True*False

False/True

s="TRUE"

type(s)

s=True

type(s)

t="Batch name is Information Technology"

t[0:33:6]

t[0:36:88]

t[-1:-33:-2]

t[0:-33:-2]

t[-3:-33:-2]

l=[1,45,678,"surya",56.67,(3+4j)]

l[0]

type(l)

s="Ramswaroop"

s.count("o")

s.count(' ')

s

s.find('a')

s.count('')

s.lower()

s.upper()

len(s)

l[::-1]

l[5]

l

l.append(67)

l

l.pop()

l.pop()

l.insert(0,456)

l

e=(1,34,56,78,89,90,"akshat",True,False)

len(e[6])

len(e)

dict={"name":"age","Ramesh":56,"Kamlesh":89}

dict["name"]

dict["Kamlesh"]

l

marks=81
if marks >= 90:
    print("Grade A+")
elif marks >= 80:
    print("Grade A")
elif marks >= 70:
    print("Grade B+")
elif marks >= 60:
    print("Grade B")
else:
    print("Grade F")

menu ={
    "Cold Tea":90,
    "Red Sauce Pasta":170,
    "Pizza":150,
    "Burger":120,
    "Ice Cream":100,
    "Coffee":100
}
print("Welcome to our Cafe")
print(menu)
order_amount=0
while True:)
    print (f"your total bill {order_amount}")

menu ={
    "Cold Tea":90,
    "Red Sauce Pasta":170,
    "Pizza":150,
    "Burger":120,
    "Ice Cream":100,
    "Coffee":100
}
print("Welcome to our Cafe")
print(menu)
order_total=0 # Changed from order_amount to order_total for consistency
while True:
  order_item=input("\nEnter the food item (or type 'done' to finish ordering): ").strip() # Added strip and prompt for finishing
  if order_item.lower() == 'done':
    break # Exit the loop if user types 'done'

  if order_item in menu:
    order_total += menu[order_item]
    print (f"Your item '{order_item}' has been added to your order.")
  else:
    print(f"Ordered item '{order_item}' is not available yet!")

  # Removed complex nested logic for simplicity and correctness in a single loop
  # User can just keep entering items or 'done'

print(f"\nYour total bill is: {order_total}") # Corrected f-string and final print

