# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nSTHGr-Cv-aodWlCDNyUmGs4Qv3m8Xm2
"""

hindi = int(input("Enter your marks in Hindi : "))
english = int(input("Enter your marks in English : "))
tafl = int(input("Enter your marks in TAFL : "))
social_studies = int(input("Enter your marks in Social Studies : "))
history = int(input("Enter your marks in History : "))

total_marks = (hindi + english + tafl + social_studies + history)
percentage = total_marks / 500 * 100

print(f"Your SGPA is {percentage / 9.5}")

dict = {
    "Hindi": hindi,
    "English": english,
    "TAFL": tafl,
    "Social Studies": social_studies,
    "History": history
}

for i in dict.keys():
    marks = dict[i]
    if marks >= 80:
        print(f"{i}-->A")
    elif marks >= 60:
        print(f"{i}-->B")
    elif marks >= 50:
        print(f"{i}-->C")
    elif marks >= 40:
        print(f"{i}-->D")
    else:
        print(f"{i}-->F")